[[layers]]
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"
name = "autocomplete"

[[layers]]
default_height = 30
default_position = "top"
name = "shell"

[[layers]]
enable = false
name = "core#statusline"

[[layers]]
enable = false
name = "core#tabline"

[[layers]]
name = "VersionControl"

[[layers]]
name = "checkers"

[[layers]]
name = "colorscheme"

[[layers]]
name = "fzf"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#json"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#php"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#xml"

[options]
buffer_index_type = 4
colorscheme = "$BASE16_THEME"
colorscheme_bg = "dark"
custom_plugins = [["chriskempson/base16-vim"]]
default_indent = 4
enable_statusline_display_mode = true
filetype_icon = true
guifont = "FuraCodeNerdFontComplete-Light 12"
relativenumber = false
statusline_inactive_separator = "arrow"
statusline_separator = "arrow"
